### ISSUE TITLE
Possible unicode handling problem 

### ISSUE THREAD

**Issue by rdhyee** [gitenberg-dev/metadata#10]
This problem first report in the context of getting unicode handling done correctly in metadata.yaml files.  Seth identified something funny in https://github.com/GITenberg/A-Journey-into-the-Interior-of-the-Earth_3748/blob/0234a8c9857a5aee506b4906c5f1d8a810112002/metadata.yaml#L15:  

> Verne, Jules Gabri\xEBl

I think there is a unicode problem in the SQL file from https://www.flowdock.com/app/gluejar/gitenberg/threads/qXafFRV5K4WM0sVN6Qp16s0qt20 --> see output from a django shell_plus session looking at the Verne book: https://gist.github.com/rdhyee/b21728bc8e1016442ced#file-django_shell_plus_output-txt-L114

You should not be able to ascii encode the YAML coming from the Verne book given the non-ascii characters.

See https://www.flowdock.com/app/gluejar/gitenberg/threads/LUnWL3NDrZpvOhR6NdWcfwcSSGF for context of flowdock discussion.

**Comment by eshellman** [comment]
it's correct in the rdf, not in the yaml

**Comment by sethwoodworth** [comment]
> In [4]: b.yaml
> Out[4]: u'_repo:
> A-Journey-into-the-Interior-of-the-Earth_3748\nalternative_title: Voyage au
> centre de la terre. English\ncontributor:\n  translator:\n    agent_name:
> Malleson, F. A. (Frederick Amadeus)\n    alias: Malleson, Frederick
> Amadeus\n    birthdate: 1819\n    deathdate: 1897\n    gutenberg_agent_id:
> \'35271\'\n    url: http://www.gutenberg.org/2009/agents/35271\ncreator:\n
>  author:\n    agent_name: Verne, Jules\n    aliases:\n    - "Verne, Jules
> Gabri\xEBl"\n    - Verne, Jules Gabriel\n    - "Verne, J\xFAlio"\n
>  birthdate: 1828\n    deathdate: 1905\n    gutenberg_agent_id: \'60\'\n
>  url: http://www.gutenberg.org/2009/agents/60\n    wikipedia:\n    -
> http://en.wikipedia.org/wiki/Jules_Verne\n    -
> http://fr.wikipedia.org/wiki/Jules_Verne\n    - "
> http://pt.wikipedia.org/wiki/J\\xFAlio_Verne"\ndescription: "Date of origin
> in French, 1864.\r\nSee also PG#18857 for the common\\n  \ English
> re-write version, The Journey to the Centre of the
> Earth."\ngutenberg_bookshelf:\n- Best Books Ever Listings\n- Science
> Fiction\ngutenberg_issued: \'2003-02-01\'\ngutenberg_type:
> Text\nidentifiers:\n  gutenberg: \'3748\'\nlanguage: en\npublication_note:
> \'London :  Ward, Lock, &Co., Ltd.,  1877\'\npublisher: Project
> Gutenberg\nrights: Public domain in the USA.\nrights_url:
> http://creativecommons.org/about/pdm\nsubjects:\n- \'!lcsh:Earth (Planet)
> -- Core -- Fiction\'\n- \'!lcc:PQ\'\n- \'!lcsh:Voyages, Imaginary --
> Fiction\'\n- \'!lcsh:Adventure stories\'\n- \'!lcsh:Science
> fiction\'\ntitle: A Journey into the Interior of the Earth\nurl:
> http://www.gutenberg.org/ebooks/3748\n'

```
b = Book.objects.get(book_id=3748)
```

The DB returns this url encoding.  Lets see if we can fix it.

**Comment by eshellman** [comment]
I'll chase.

**Comment by eshellman** [comment]
fixed with PR#11
