### ISSUE TITLE
Add key for book source file

### ISSUE THREAD

**Issue by sethwoodworth** [gitenberg-dev/metadata#16]
metadata.yaml will eventually be in every repo.  It is not currently possible to know which file in a repo contains the book text, let alone the _best_ version of a book.

For now, we can add something that points to book.asciidoc to all of the Second Folio repos

**Comment by samwilson** [comment]
Is there a key to be used to point to the source _scans_? Or an Internet Archive ID or something? (I've been seeking out scans against which to proofread, and just adding a link to the readme. [(e.g.)](https://github.com/samwilson/News_From_Nowhere/blob/master/README.rst#technical-details))

**Comment by eshellman** [comment]
The metadata dictionary https://github.com/gitenberg-dev/documentation/blob/master/metadata/pandata_attribute_dictionary.yaml https://github.com/gitenberg-dev/documentation/blob/master/metadata/pandata_attribute_dictionary.yaml  defines
ocr_file_link: A url leading to the OCR files or OCRed image related to this book,

added based on discussion with you.

**Comment by samwilson** [comment]
Oh cool! :) Thanks for pointing it out. (Sorry, I should've looked harder; was searching for 'scan'...)

**Comment by eshellman** [comment]
closing this because the metadata module will be merged into gitenberg-dev/gitberg. Add issues elsewhere as needed
